[loggers]
keys=root,fun

[logger_root]
level=INFO
handlers=terminal,file

[logger_fun]
qualname=fun
handlers=null
level=DEBUG

[handlers]
keys=null,terminal,file

[handler_null]
class=NullHandler

[handler_terminal]
class=StreamHandler
formatter=terminal

[handler_file]
class=FileHandler
formatter=file
level=DEBUG
args=("fun.log","w","UTF-8",True)

[formatters]
keys=terminal,file

[formatter_terminal]
class=fun.utils.formatters.ColoringIndentingFormatter
format=%(asctime)s.%(msecs)03d [%(levelname).4s][%(name)s]: %(message)s
datefmt=%Y.%m.%d %H:%M:%S

[formatter_file]
class=fun.utils.formatters.IndentingFormatter
format=%(asctime)s.%(msecs)03d [%(levelname).4s][%(name)s]: %(message)s
datefmt=%Y.%m.%d %H:%M:%S