#!/bin/bash

sbatch -J "2Sweep-Diff-64x64-1"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-1"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-1/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-2"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-2"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-2/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-3"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-3"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-3/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-4"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-4"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-4/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-5"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-5"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-5/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-10"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-10"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-10/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-11"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-11"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-11/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-12"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-12"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-12/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-13"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-13"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-13/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-14"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-14"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-14/weights/best-all.pt
sbatch -J "2Sweep-Diff-64x64-15"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-64x64-15"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-64x64-15/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-1"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-1"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-1/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-2"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-2"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-2/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-3"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-3"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-3/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-4"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-4"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-4/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-5"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-5"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-5/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-10" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-10/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-11"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-11" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-11/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-12"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-12" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-12/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-13"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-13" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-13/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-14"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-14" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-14/weights/best-all.pt
sbatch -J "2Sweep-Diff-128x128-15"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-128x128-15" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-128x128-15/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-1"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-1"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-1/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-2"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-2"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-2/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-3"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-3"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-3/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-4"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-4"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-4/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-5"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-5"  --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-5/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-10" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-10/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-11"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-11" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-11/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-12"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-12" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-12/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-13"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-13" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-13/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-14"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-14" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-14/weights/best-all.pt
sbatch -J "2Sweep-Diff-256x256-15"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-256x256-15" --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-256x256-15/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-1"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-1"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-1/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-2"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-2"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-2/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-3"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-3"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-3/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-4"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-4"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-4/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-5"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-5"    --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-5/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-10"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-10"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-10/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-11"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-11"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-11/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-12"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-12"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-12/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-13"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-13"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-13/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-14"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-14"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-14/weights/best-all.pt
sbatch -J "2Sweep-Diff-mixed-15"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-Diff-mixed-15"   --model=diff --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/Diff-mixed-15/weights/best-all.pt

sbatch -J "2Sweep-UNO-64x64-1"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-1"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-1/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-2"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-2"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-2/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-3"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-3"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-3/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-4"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-4"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-4/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-5"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-5"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-5/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-10"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-10"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-10/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-11"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-11"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-11/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-12"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-12"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-12/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-13"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-13"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-13/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-14"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-14"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-14/weights/best-all.pt
sbatch -J "2Sweep-UNO-64x64-15"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-64x64-15"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-64x64-15/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-1"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-1"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-1/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-2"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-2"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-2/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-3"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-3"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-3/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-4"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-4"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-4/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-5"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-5"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-5/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-10" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-10/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-11"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-11" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-11/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-12"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-12" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-12/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-13"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-13" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-13/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-14"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-14" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-14/weights/best-all.pt
sbatch -J "2Sweep-UNO-128x128-15"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-128x128-15" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-128x128-15/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-1"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-1"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-1/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-2"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-2"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-2/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-3"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-3"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-3/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-4"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-4"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-4/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-5"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-5"  --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-5/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-10" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-10/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-11"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-11" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-11/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-12"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-12" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-12/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-13"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-13" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-13/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-14"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-14" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-14/weights/best-all.pt
sbatch -J "2Sweep-UNO-256x256-15"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-256x256-15" --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-256x256-15/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-1"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-1"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-1/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-2"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-2"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-2/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-3"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-3"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-3/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-4"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-4"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-4/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-5"      $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-5"    --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-5/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-10"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-10"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-10/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-11"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-11"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-11/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-12"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-12"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-12/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-13"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-13"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-13/weights/best-all.pt
sbatch -J "2Sweep-UNO-mixed-14"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-UNO-mixed-14"   --model=uno --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/UNO-mixed-14/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "2CNO-64x64-1"          $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-1"          --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-1"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-264x641"    --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-2"          $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-2"          --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-2"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-264x642"    --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-3"          $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-3"          --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-3"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-264x643"    --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-4"          $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-4"          --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-4"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-264x644"    --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-5"          $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-5"          --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-5"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-264x645"    --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-11"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-11"         --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-11"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-64x64-11"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-12"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-12"         --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-12"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-64x64-12"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-13"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-13"         --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-13"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-64x64-13"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-14"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-14"         --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-14"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-64x64-14"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-64x64-15"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-64x64-15"         --model=cno --dataset=ellipses-64x64   --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-64x64-15"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-64x64-15"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/2CNO-64x64-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-1"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-1"        --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-1"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-1"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-2"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-2"        --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-2"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-2"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-3"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-3"        --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-3"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-3"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-4"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-4"        --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-4"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-4"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-5"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-5"        --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-5"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-5"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-11"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-11"       --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-11" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-11" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-12"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-12"       --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-12" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-12" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-13"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-13"       --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-13" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-13" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-14"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-14"       --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-14" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-14" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-128x128-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-128x128-15"       --model=cno --dataset=ellipses-128x128 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-128x128-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-128x128-15" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/2CNO-128x128-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-1"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-1"        --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-1"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-1"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-2"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-2"        --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-2"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-2"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-3"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-3"        --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-3"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-3"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-4"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-4"        --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-4"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-4"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-5"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-5"        --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-5"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-5"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-11"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-11"       --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-11" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-11" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-12"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-12"       --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-12" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-12" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-13"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-13"       --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-13" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-13" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-14"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-14"       --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-14" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-14" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-256x256-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-256x256-15"       --model=cno --dataset=ellipses-256x256 --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-256x256-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-256x256-15" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/2CNO-256x256-15/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-1"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-1"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-1"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-1"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-2"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-2"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-2"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-2"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-3"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-3"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-3"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-3"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-4"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-4"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-4"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-4"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-5"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-5"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-5"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-5"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-11"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-11"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-11"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-11"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-12"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-12"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-12"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-12"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-13"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-13"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-13"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-13"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-14"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-14"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-14"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-14"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed64-15"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed64-15"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed64-15"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed64-15"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed64-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-1"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-1"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-1"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-1"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-2"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-2"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-2"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-2"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-3"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-3"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-3"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-3"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-4"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-4"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-4"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-4"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-5"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-5"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-5"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-5"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-11"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-11"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-11" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-11" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-12"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-12"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-12" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-12" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-13"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-13"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-13" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-13" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-14"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-14"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-14" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-14" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed128-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed128-15"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed128-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed128-15" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed128-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-1"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-1"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-1"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-1"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-2"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-2"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-2"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-2"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-3"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-3"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-3"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-3"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-4"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-4"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-4"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-4"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-5"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-5"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-5"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-5"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-11"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-11"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-11" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-11" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-12"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-12"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-12" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-12" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-13"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-13"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-13" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-13" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-14"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-14"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-14" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-14" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "2CNO-rmixed256-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2CNO-rmixed256-15"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=4  --accumulation-steps=8)
sbatch --dependency=afterok:$JOBID -J "2Sweep-CNO-rmixed256-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="2Sweep-CNO-rmixed256-15" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/2CNO-rmixed256-15/weights/best-all.pt
