#!/bin/bash

# Sweep resized
# Sweep CNO again
# Sweep FNO again

sbatch -J "Sweep-CNO-64x64-1"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-1"    --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-1/weights/best-all.pt
sbatch -J "Sweep-CNO-64x64-2"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-2"    --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-2/weights/best-all.pt
sbatch -J "Sweep-CNO-64x64-3"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-3"    --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-3/weights/best-all.pt
sbatch -J "Sweep-CNO-64x64-4"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-4"    --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-4/weights/best-all.pt
sbatch -J "Sweep-CNO-64x64-5"    $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-5"    --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-5/weights/best-all.pt
sbatch -J "Sweep-CNO-64x64-11"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-11"   --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-11/weights/best-all.pt
sbatch -J "Sweep-CNO-64x64-12"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-12"   --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-12/weights/best-all.pt
sbatch -J "Sweep-CNO-64x64-13"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-13"   --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-13/weights/best-all.pt
sbatch -J "Sweep-CNO-64x64-14"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-14"   --model=cno --dataset=ellipses-sweep --resize-input-size=64  --batch-size=32 --test-only --weights=runs/CNO-64x64-14/weights/best-all.pt
sbatch -J "Sweep-CNO-128x128-11" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-128x128-11" --model=cno --dataset=ellipses-sweep --resize-input-size=128 --batch-size=32 --test-only --weights=runs/CNO-128x128-11/weights/best-all.pt
sbatch -J "Sweep-CNO-128x128-12" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-128x128-12" --model=cno --dataset=ellipses-sweep --resize-input-size=128 --batch-size=32 --test-only --weights=runs/CNO-128x128-12/weights/best-all.pt
sbatch -J "Sweep-CNO-128x128-13" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-128x128-13" --model=cno --dataset=ellipses-sweep --resize-input-size=128 --batch-size=32 --test-only --weights=runs/CNO-128x128-13/weights/best-all.pt
sbatch -J "Sweep-CNO-128x128-14" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-128x128-14" --model=cno --dataset=ellipses-sweep --resize-input-size=128 --batch-size=32 --test-only --weights=runs/CNO-128x128-14/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "CNO-64x64-15"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-64x64-15"         --model=cno --dataset=ellipses-64x64   --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-64x64-15"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-15"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/CNO-64x64-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-128x128-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-128x128-15"       --model=cno --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-128x128-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-128x128-15" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/CNO-128x128-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-128x128-1"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-128x128-1"        --model=cno --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-128x128-1"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-128x128-1"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/CNO-128x128-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-128x128-2"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-128x128-2"        --model=cno --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-128x128-2"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-128x128-2"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/CNO-128x128-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-128x128-3"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-128x128-3"        --model=cno --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-128x128-3"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-128x128-3"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/CNO-128x128-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-128x128-4"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-128x128-4"        --model=cno --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-128x128-4"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-128x128-4"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/CNO-128x128-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-128x128-5"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-128x128-5"        --model=cno --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-128x128-5"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-128x128-5"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/CNO-128x128-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-128x128-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-128x128-15"       --model=cno --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-128x128-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-128x128-15"  --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/CNO-128x128-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-1"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-1"        --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-1"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-256x256-1"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-2"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-2"        --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-2"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-256x256-2"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-3"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-3"        --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-3"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-256x256-3"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-4"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-4"        --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-4"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-256x256-4"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-5"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-5"        --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-5"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CSweep-O-256x256-5"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-11"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-11"       --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-11" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-256x256-11" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-12"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-12"       --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-12" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-256x256-12" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-13"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-13"       --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-13" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-256x256-13" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-14"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-14"       --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-14" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-256x256-14" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-15"       --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-256x256-15" --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-15/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "CNO-rmixed64-1"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-1"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-1"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-1"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-2"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-2"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-2"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-2"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-3"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-3"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-3"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-3"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-4"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-4"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-4"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-4"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-5"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-5"         --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-5"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-5"   --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-11"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-11"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-11"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-11"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-12"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-12"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-12"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-12"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-13"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-13"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-13"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-13"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-14"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-14"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-14"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-14"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed64-15"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-15"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-15"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-15"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-1"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-1"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-1"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-1"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-2"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-2"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-2"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-2"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-3"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-3"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-3"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-3"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-4"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-4"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-4"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-4"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-5"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-5"        --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-5"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-5"  --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-11"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-11"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-11" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-11" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-12"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-12"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-12" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-12" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-13"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-13"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-13" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-13" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-14"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-14"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-14" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-14" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-15"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-15" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-1"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-1"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-1"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-1"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-1/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-2"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-2"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-2"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-2"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-2/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-3"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-3"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-3"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-3"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-3/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-4"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-4"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-4"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-4"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-4/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-5"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-5"        --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-5"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-5"  --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-5/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-11"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-11"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-11" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-11" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-11/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-12"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-12"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-12" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-12" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-12/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-13"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-13"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-13" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-13" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-13/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-14"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-14"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-14" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-14" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-15"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-15" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-15/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "UNO-128x128-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNO-128x128-15"       --model=uno --dataset=ellipses-128x128 --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNO-128x128-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNO-128x128-15" --model=uno --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNO-128x128-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNO-256x256-15"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNO-256x256-15"       --model=uno --dataset=ellipses-256x256 --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNO-256x256-15" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNO-256x256-15" --model=uno --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNO-256x256-15/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNO-mixed-14"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNO-mixed-14"         --model=uno --dataset=ellipses-mixed   --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNO-mixed-14"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNO-mixed-14"   --model=uno --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNO-mixed-14/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNO-mixed-15"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNO-mixed-15"         --model=uno --dataset=ellipses-mixed   --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNO-mixed-15"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNO-mixed-15"   --model=uno --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNO-mixed-15/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "UNet-64x64-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNet-64x64-10"         --model=unet-custom --dataset=ellipses-64x64   --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNet-64x64-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNet-64x64-10"   --model=unet-custom --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNet-64x64-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNet-128x128-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNet-128x128-10"       --model=unet-custom --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNet-128x128-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNet-128x128-10" --model=unet-custom --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNet-128x128-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNet-256x256-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNet-256x256-10"       --model=unet-custom --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNet-256x256-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNet-256x256-10" --model=unet-custom --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNet-256x256-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNet-mixed-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNet-mixed-10"         --model=unet-custom --dataset=ellipses-mixed   --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNet-mixed-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNet-mixed-10"   --model=unet-custom --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNet-mixed-10/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "Diff-64x64-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Diff-64x64-10"         --model=diff --dataset=ellipses-64x64   --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-Diff-64x64-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-Diff-64x64-10"   --model=diff --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/Diff-64x64-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "Diff-128x128-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Diff-128x128-10"       --model=diff --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-Diff-128x128-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-Diff-128x128-10" --model=diff --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/Diff-128x128-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "Diff-256x256-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Diff-256x256-10"       --model=diff --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-Diff-256x256-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-Diff-256x256-10" --model=diff --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/Diff-256x256-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "Diff-mixed-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Diff-mixed-10"         --model=diff --dataset=ellipses-mixed   --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-Diff-mixed-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-Diff-mixed-10"   --model=diff --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/Diff-mixed-10/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "FNO-64x64-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="FNO-64x64-10"         --model=specRes --dataset=ellipses-64x64   --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-FNO-64x64-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-FNO-64x64-10"   --model=specRes --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/FNO-64x64-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "FNO-128x128-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="FNO-128x128-10"       --model=specRes --dataset=ellipses-128x128 --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-FNO-128x128-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-FNO-128x128-10" --model=specRes --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/FNO-128x128-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "FNO-256x256-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="FNO-256x256-10"       --model=specRes --dataset=ellipses-256x256 --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-FNO-256x256-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-FNO-256x256-10" --model=specRes --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/FNO-256x256-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "FNO-mixed-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="FNO-mixed-10"         --model=specRes --dataset=ellipses-mixed   --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-FNO-mixed-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-FNO-mixed-10"   --model=specRes --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/FNO-mixed-10/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "UFNO-64x64-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UFNO-64x64-10"         --model=specResU --dataset=ellipses-64x64   --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UFNO-64x64-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UFNO-64x64-10"   --model=specResU --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UFNO-64x64-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UFNO-128x128-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UFNO-128x128-10"       --model=specResU --dataset=ellipses-128x128 --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UFNO-128x128-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UFNO-128x128-10" --model=specResU --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UFNO-128x128-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UFNO-256x256-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UFNO-256x256-10"       --model=specResU --dataset=ellipses-256x256 --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UFNO-256x256-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UFNO-256x256-10" --model=specResU --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UFNO-256x256-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UFNO-mixed-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UFNO-mixed-10"         --model=specResU --dataset=ellipses-mixed   --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UFNO-mixed-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UFNO-mixed-10"   --model=specResU --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UFNO-mixed-10/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "UNO-64x64-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNO-64x64-10"         --model=uno  --dataset=ellipses-64x64   --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNO-64x64-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNO-64x64-10"   --model=uno  --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNO-64x64-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNO-128x128-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNO-128x128-10"       --model=uno  --dataset=ellipses-128x128 --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNO-128x128-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNO-128x128-10" --model=uno  --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNO-128x128-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNO-256x256-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNO-256x256-10"       --model=uno  --dataset=ellipses-256x256 --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNO-256x256-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNO-256x256-10" --model=uno  --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNO-256x256-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "UNO-mixed-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="UNO-mixed-10"         --model=uno  --dataset=ellipses-mixed   --batch-size=1  --accumulation-steps=32 --cpu-opt-state)
sbatch --dependency=afterok:$JOBID -J "Sweep-UNO-mixed-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-UNO-mixed-10"   --model=uno  --dataset=ellipses-sweep   --batch-size=32 --test-only --weights=runs/UNO-mixed-10/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "CNO-64x64-10"           $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-64x64-10"           --model=cno --dataset=ellipses-64x64   --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-64x64-10"     $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-64x64-10"     --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=64  --test-only --weights=runs/CNO-64x64-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-128x128-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-128x128-10"         --model=cno --dataset=ellipses-128x128 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-128x128-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-128x128-10"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=128 --test-only --weights=runs/CNO-128x128-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-256x256-10"         $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-256x256-10"         --model=cno --dataset=ellipses-256x256 --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-256x256-10"   $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="Sweep-CNO-256x256-10"   --model=cno --dataset=ellipses-sweep   --batch-size=32 --resize-input-size=256 --test-only --weights=runs/CNO-256x256-10/weights/best-all.pt

JOBID=$(sbatch --parsable          -J "CNO-rmixed64-10"        $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed64-10"        --model=cno --resize-input-size=64  --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed64-10"  $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed64-10"  --model=cno --resize-input-size=64  --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed64-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed128-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed128-10"       --model=cno --resize-input-size=128 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed128-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed128-10" --model=cno --resize-input-size=128 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed128-10/weights/best-all.pt
JOBID=$(sbatch --parsable          -J "CNO-rmixed256-10"       $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-rmixed256-10"       --model=cno --resize-input-size=256 --dataset=ellipses-mixed --batch-size=32)
sbatch --dependency=afterok:$JOBID -J "Sweep-CNO-rmixed256-10" $(dirname "$0")/omni.submit.sh --model-save-freq=9999 --forced-run-name="CNO-Sweep-rmixed256-10" --model=cno --resize-input-size=256 --dataset=ellipses-sweep --batch-size=32 --test-only --weights=runs/CNO-rmixed256-10/weights/best-all.pt
